[2024-05-22T12:18:58.014+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T12:18:58.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weater_api_ready scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-22T12:18:58.216+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weater_api_ready scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-22T12:18:58.217+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-22T12:18:58.527+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weater_api_ready> on 2024-05-21 00:00:00+00:00
[2024-05-22T12:18:58.594+0000] {standard_task_runner.py:63} INFO - Started process 5006 to run task
[2024-05-22T12:18:58.689+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weater_api_ready', 'scheduled__2024-05-21T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp71jma2gn']
[2024-05-22T12:18:58.705+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask is_weater_api_ready
[2024-05-22T12:18:58.957+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weater_api_ready scheduled__2024-05-21T00:00:00+00:00 [running]> on host ubuntu2204
[2024-05-22T12:18:59.695+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weater_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T00:00:00+00:00'
[2024-05-22T12:18:59.698+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T12:18:59.699+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-22T12:18:59.699+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Kyiv&appid=a2fc2ab52b832be75e0040a88f3e406a
[2024-05-22T12:18:59.763+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-05-22T12:19:00.442+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-22T12:19:00.444+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T12:19:01.264+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weater_api_ready, run_id=scheduled__2024-05-21T00:00:00+00:00, execution_date=20240521T000000, start_date=20240522T121858, end_date=20240522T121901
[2024-05-22T12:19:01.606+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T12:19:01.671+0000] {logging_mixin.py:188} WARNING - /home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
[2024-05-22T12:19:01.749+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T12:19:01.886+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
