[2024-05-22T13:51:04.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T13:51:04.983+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.is_weater_api_ready manual__2024-05-22T13:50:32.868472+00:00 [queued]>
[2024-05-22T13:51:04.992+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.is_weater_api_ready manual__2024-05-22T13:50:32.868472+00:00 [queued]>
[2024-05-22T13:51:04.993+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-22T13:51:05.060+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): group_a.is_weater_api_ready> on 2024-05-22 13:50:32.868472+00:00
[2024-05-22T13:51:05.073+0000] {standard_task_runner.py:63} INFO - Started process 44666 to run task
[2024-05-22T13:51:05.092+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'group_a.is_weater_api_ready', 'manual__2024-05-22T13:50:32.868472+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmpv2mug6al']
[2024-05-22T13:51:05.096+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask group_a.is_weater_api_ready
[2024-05-22T13:51:05.205+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.group_a.is_weater_api_ready manual__2024-05-22T13:50:32.868472+00:00 [running]> on host ubuntu2204
[2024-05-22T13:51:05.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='group_a.is_weater_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T13:50:32.868472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T13:50:32.868472+00:00'
[2024-05-22T13:51:05.482+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T13:51:05.557+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-22T13:51:05.563+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Kyiv&appid=a2fc2ab52b832be75e0040a88f3e406a
[2024-05-22T13:51:05.584+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-05-22T13:51:06.282+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-22T13:51:06.285+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T13:51:06.299+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag_parallel, task_id=group_a.is_weater_api_ready, run_id=manual__2024-05-22T13:50:32.868472+00:00, execution_date=20240522T135032, start_date=20240522T135104, end_date=20240522T135106
[2024-05-22T13:51:06.387+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T13:51:06.419+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T13:51:06.435+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
